### ISSUE TITLE
Electron's Info.plist missing

### ISSUE THREAD

**Issue by rcharant** [simonhamp/cronikl#1]
I am seeing this error when I tried running php artisan native:serve command:

```
Starting NativePHP dev server…
Fetching latest dependencies…
Starting NativePHP app…

   ErrorException

  file_get_contents(/Users/rajiv/Code/cronikl/vendor/nativephp/electron/src/Commands/../../resources/js/node_modules/electron/dist/Electron.app/Contents/Info.plist): Failed to open stream: No such file or directory

  at vendor/nativephp/electron/src/Commands/DevelopCommand.php:62
     58▕      * @return void
     59▕      */
     60▕     protected function patchPlist()
     61▕     {
  ➜  62▕         $pList = file_get_contents(__DIR__.'/../../resources/js/node_modules/electron/dist/Electron.app/Contents/Info.plist');
     63▕
     64▕         // Change the CFBundleName to the correct app name
     65▕         $pattern = '/(<key>CFBundleName<\/key>\s+<string>)(.*?)(<\/string>)/m';
     66▕         $pList = preg_replace($pattern, '$1'.config('app.name').'$3', $pList);

      +14 vendor frames

  15  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

I followed step by step. Please let me know if I am missing anything here. I have zero knowledge on Electron.

**Comment by jmendozaf** [comment]
> I am seeing this error when I tried running php artisan native:serve command:
> 
> ```
> Starting NativePHP dev server…
> Fetching latest dependencies…
> Starting NativePHP app…
> 
>    ErrorException
> 
>   file_get_contents(/Users/rajiv/Code/cronikl/vendor/nativephp/electron/src/Commands/../../resources/js/node_modules/electron/dist/Electron.app/Contents/Info.plist): Failed to open stream: No such file or directory
> 
>   at vendor/nativephp/electron/src/Commands/DevelopCommand.php:62
>      58▕      * @return void
>      59▕      */
>      60▕     protected function patchPlist()
>      61▕     {
>   ➜  62▕         $pList = file_get_contents(__DIR__.'/../../resources/js/node_modules/electron/dist/Electron.app/Contents/Info.plist');
>      63▕
>      64▕         // Change the CFBundleName to the correct app name
>      65▕         $pattern = '/(<key>CFBundleName<\/key>\s+<string>)(.*?)(<\/string>)/m';
>      66▕         $pList = preg_replace($pattern, '$1'.config('app.name').'$3', $pList);
> 
>       +14 vendor frames
> 
>   15  artisan:35
>       Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> ```
> 
> I followed step by step. Please let me know if I am missing anything here. I have zero knowledge on Electron.

same!

**Comment by kuztom** [comment]
Same for me

**Comment by Novica89** [comment]
Yeap. It's broken

**Comment by dib258** [comment]
I have the same error,

I tried to go to `<project_folder>/vendor/nativephp/electron/resources/js` and run `npm install` 

This solve the missing `node_modules` folder with the `Info.plist` from Electron.

Then I was able to build the app but there was some javascript error when launching.

I then tried in the root of the `project_folder` to also run `npm install` (more depedencies where installed)

Now the app can build without any problem but it seems I cannot see the app. (it loaded but doesn't show on screen)

But no more error ! (That's a first win for me xD)

**Comment by dib258** [comment]
Tried `php artisan native:build` 

And now It seems there's a missing `php.js` file in the same folder where the `Info.plist` was missing.

`Error: Cannot find module '<project_folder>/vendor/nativephp/electron/resources/js/php.js'`

That I don't know how to fix, maybe what I tried in the previous post wasn't the right way to do it!

**Comment by radermacher** [comment]
**SOLUTION to get php artisan native:serve working**
Run `composer require nativephp/electron` to use the latest release than dev-main.
Before `php artisan native:serve` you have to run `php artisan native:install` and `npm install` and `npm run build`.
you also have to ensure you have `yarn`installed → `brew install yarn`

**Comment by dib258** [comment]
Thanks @radermacher those are steps getting us closer to see the result! :D 

I have no error at all but still can't get to see the app. It's running, I have the icon in the iconbar, but can get it to show.

When the server is running I can see that message : 
`[Fri Jul 21 16:50:44 2023] Failed to listen on 127.0.0.1:8100 (reason: Address already in use)`

and when I do `sudo lsof -i tcp -nP | grep 127.0.0.1:8100` to see all the connection listening I have the following .

`php       66872 dib258    3u  IPv4 0xc80c02fad34986cd      0t0  TCP 127.0.0.1:8100 (LISTEN)`

I tried to stop the PHP version from running  like this : ` brew services stop php`

But still there's still a php version squatting the `127.0.0.1:8100`

**Comment by donardo** [comment]
* Cronikl currently supports **macOS** only, but Linux and Windows support is coming.

**Comment by dib258** [comment]
Hello @donardo,

I'm currently on macOS :)

**Comment by khanakia** [comment]
Same issue on macos

**Comment by simonhamp** [comment]
Updated README should sort this issue out

`native:build` problems are separate (see #2)
